### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by sa-lee** [steveped/ngsReports#3]
Hi Stephen and team,

Firstly can I say that I really like the look of this package and think it's a great idea to implement an R version of common qc tasks. I really enjoyed the talk you gave at biocasia. The work you've done so far looks really great! 

I just had a few suggestions/comments that I think could be interesting to implement.

1.  Alternative colours: I noticed that you are using a similar colour set to the fastqc html report, generally it's probably a better idea to use a diverging colour palette so differences are emphasised (see [here](http://www.personal.psu.edu/cab38/Pub_scans/Brewer_1999_Color-Use-Guidelines-ASAproc.pdf) for why this is a good idea) you can use these in ggplot2 with `scale_colour_brewer` http://ggplot2.tidyverse.org/reference/scale_brewer.html (set 2 is a colour blind friendly palette). In my opinion these also make for more "aesthetically" pleasing graphics too.

2. Disabling plotly features. In a heatmap it doesn't make sense to be able to zoom. These features can be modified with `plotly::config` and `plotly::layout`. See also https://community.plot.ly/t/disable-interactions-in-plotly-for-r-and-ggplot2/1361.

3. Speaking of heatmaps, an alternative that may be faster to render is a parallel coordinates plot (these are also generally thought to be perceptually better due to no longer encoding values to a colour). You can make these in ggplot2 style with `GGally::ggparcoord`.  

4. Large samples, a nifty feature of multiqc is the beeswarm plots that implemented when sample size grows. 

Looking forward to seeing how this project evolves.

Thanks,
Stuart

**Comment by steveped** [comment]
Hi Stuart,

Thanks for taking the time to look through things & put down those suggestions.

1. Good point. We've left the default as similar to the FastQC report for easy interpretation. This really only applies to things like `plotAdapterContent()` and `plotBaseQualities()` where there are clearly defined PASS/WARN/FAIL criteria. For other heatmaps we've chosen `viridisLite::inferno()` which I'm not sure about the colour-blind status. I'll chase that up. The good news is that for metrics with a clear PASS/WARN/FAIL criteria, users can supply their own colour scheme, via an object of class `PwfCols`. I'll make sure I add this to the vignette so this is clear.

2. When there are large sample numbers, clicking on the status bar can be difficult. I've left zooming enabled to make this easier, but we'll have a play with this with a couple of larger datasets and see how it responds.

3. Thanks for the tip! I'll check it out.

4. Again, thanks for the tip! I'll check that out too.

Cheers & I also really liked `plyranges`. I'd just been discussing as an idea that with someone the day before so I think it'll be rally useful.

Steve
