### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by scseekers** [steveped/ngsReports#30]
Hi @steveped 

I really like this package and am using it to report my Star Alignments results. This is a feature request to plot the percentage of Uniquely mapped reads, multi mapped and unmapped reads. It's more informative to plot percentage to get a ballpark idea of how much %age of your data is aligning uniquely or not aligning at all. I couldn't do that with `plotAlignmentsummary` function.

However, `importNgsLogs` is really cool and I will club it with ggplot for my purpose till then for barplot.

**Comment by steveped** [comment]
Hi @scseekers . Thanks for that request & you inadvertently alerted me to a bug. I've added this to version 1.7.1 via the `asPercent` argument. It's currently building on travis & I'll push to Bioc once I'm happy with all the tests.

**Comment by steveped** [comment]
Hi again @scseekers , I had my version numbers wrong for the BioC system, so it's now in version 1.6.1 & is available from Bioconductor.
