### ISSUE TITLE
Return data instead of plotting

### ISSUE THREAD

**Issue by peterkilfeather** [steveped/ngsReports#31]
Is there a way to return the data that is given to ggplot2, instead of plotting?

**Comment by steveped** [comment]
Which particular plot are you wishing to access the data for? Most of the plotting functions just do some reshaping from the `getModule()` output.

The easiest method which comes to mind if you don't want to do any reshaping would be to save the plot as an object (e.g. `p <-  plotGcContent(fdl)`  and then access the data using `p$data`.

**Comment by peterkilfeather** [comment]
It was from plotSeqContent(). Thank you, I wasn't aware of that functionality in ggplot!
