### ISSUE TITLE
import bowtie2 report incomplete

### ISSUE THREAD

**Issue by LaureTomas** [steveped/ngsReports#34]
Hi!

I'm trying to use the function `importNgsLogs` with a bowtie2 report but it gives an error. I've been checking the code of the functions and it seems that the problem comes with `ngsReports:::.isValidBowtie2Log`, since it only accepts reports for Single-end data and not Paired-end, since for paired-end data the reports contain the word "aligned **concordantly**" and then it gives FALSE in all the `grepl` lines of code.

The function itself is this one:
```
function (x) 
{
  n <- length(x)
  chkLen <- length(x) > 0
  firstLine <- grepl("reads; of these:$", x[1])
  lastLine <- grepl("overall alignment rate$", x[n])
  noAln <- sum(grepl("aligned 0 times$", x)) == 1
  alnExact <- sum(grepl("aligned exactly 1 time$", x)) == 1
  alnG1 <- sum(grepl("aligned >1 times$", x)) == 1
  all(c(chkLen, firstLine, lastLine, noAln, alnExact, alnG1))
}
```
But a bowtie2 report for paired-end data looks like this:
```
16865587 reads; of these:
  16865587 (100.00%) were paired; of these:
    1040235 (6.17%) aligned concordantly 0 times
    9789146 (58.04%) aligned concordantly exactly 1 time
    6036206 (35.79%) aligned concordantly >1 times
93.83% overall alignment rate
```

Could you solve this?

Thank you in advance.
Regards

Edit:
Going deeper I found that the function `ngsReports:::.parseBowtie2Logs` is also giving a problem because even though it is sensitive to both paired-end and single-end (it'd be great if you copy the regex from this one to the previous one), it's not sensitive to the different arguments of bowtie2. For example, if I select in bowtie2 not to report the non-aligned and the discordant reads it gives an error because it tries to generate a dataframe with them and they're missing. I've included below a line of code that could work. And the other problem is that the function computes the alignment rate, but if I don't have non-aligned reads it gives NA. I think it would be better if the function takes the alignment rate from the report itself and does not compute it.

The function is this one:
```
function (data) 
{
  df <- lapply(data, function(x) {
    x <- stringr::str_trim(x)
    paired <- grepl("were paired", x[2])
    totReads <- gsub("([0-9]*) reads; of these:", "\\1", 
                     x[1])
    noAln <- x[grep("aligned 0 times$", x)]
    noAln <- gsub("([0-9]*) .+ aligned 0 times", "\\1", noAln)
    uniq <- x[grep("aligned exactly 1 time$", x)]
    uniq <- gsub("([0-9]*) .+ aligned exactly 1 time", "\\1", 
                 uniq)
    mult <- x[grep("aligned >1 times", x)]
    mult <- gsub("([0-9]*) .+ aligned >1 times", "\\1", mult)
    pairReads <- uniqPairs <- multPairs <- uniqDiscord <- 0
    if (paired) {
      pairReads <- x[grep("were paired; of these:$", x)]
      pairReads <- gsub("([0-9]*) .+ of these:", "\\1", 
                        pairReads)
      uniqPairs <- x[grep("aligned concordantly exactly 1 time$", 
                          x)]
      uniqPairs <- gsub("([0-9]*) .+ exactly 1 time", "\\1", 
                        uniqPairs)
      multPairs <- x[grep("aligned concordantly >1 times$", 
                          x)]
      multPairs <- gsub("([0-9]*) .+ >1 times", "\\1", 
                        multPairs)
      uniqDiscord <- x[grep("aligned discordantly 1 time$", 
                            x)]
      uniqDiscord <- gsub("([0-9]*) .+ 1 time", "\\1", 
                          uniqDiscord)
    }
    out <- list(Total_Reads = totReads, Not_Aligned = noAln, 
                Unique_Unpaired = uniq, Multiple_Unpaired = mult, 
                Paired_Reads = pairReads, Unique_In_Pairs = uniqPairs, 
                Multiple_In_Pairs = multPairs, Unique_Discordant_Pairs = uniqDiscord)
    out <- lapply(out, as.integer)
    **out[unlist(lapply(out, function(x) identical(x, integer(0))))] <- NA**   ## Added by LaureTomas
    as.data.frame(out)
  })
  df <- bind_rows(df)
  df$Alignment_Rate <- 1 - df$Not_Aligned/(df$Total_Reads +  ## Better to get from the report?
                                             df$Paired_Reads)
  df$Filename <- names(data)
  dplyr::select(df, "Filename", ends_with("Reads"), contains("Unique"), 
                contains("Multiple"), everything())
}
```

**Comment by LaureTomas** [comment]
Hello again.
And sorry in advance for all the inconvenience.

Now I'm dealing with **macs2** reports and I was unable to get it right with your function and doing debug it get that was the same problem that for bowtie2. If I don't have a control sample while running macs2 there are some elements of the report that are empty with `integer(0)` or `numeric(0)` and when the function tries to turn it into a tibble it returns an empty tibble. The solution will be to include the same line that I've included in the bowtie2 report above just before turning it into a tibble:

```
    args_out[unlist(lapply(args_out, function(x) identical(x, numeric(0))))] <- NA ## Added by LaureTomas
    args_out <- as_tibble(args_out)
```

**Comment by steveped** [comment]
Hi @LaureTomas. Thanks for letting me know! Hopefully this hasn't caused too much of a problem for you. I'll try to resolve this and push to Bioconductor in the next few days. I'll let you know when I've had a chance to look at it in detail

**Comment by steveped** [comment]
Hi @LaureTomas.

I've made the changes & pushed to Bioconductor, and this should be in 3.15 as version 3.12.1, or devel as 3.13.1. It'll probably update in the next nightly build.

Thanks again for lettting me know. It's great when people with use cases I haven't come across in my own work can keep this package useable for as many as possible. 

Steve

**Comment by LaureTomas** [comment]
Hi @steveped 

I've been checking Bioconductor daily and today they updated the package from version 1.12.0 to 1.12.1. I don't see any version 3.12.1. However, when I install it (https://bioconductor.org/packages/release/bioc/src/contrib/ngsReports_1.12.1.tar.gz) the code does not change from the previous version, but in your GitHub is updated. Could it be a problem synchronising your GitHub with Bioconductor, or should I wait for a new update?

Thanks and sorry for the inconvenience.

**Comment by steveped** [comment]
Ugh. So sorry. I must've messed up the `git cherry-pick` between dev & release branches. I've just tried again & have pushed to Bioc as 1.12.2. Thanks again for being on the ball with this one. Much appreciated.

**Comment by LaureTomas** [comment]
Hi again @steveped 

Thank you so much for everything. The package is working smoothly for bowtie2 reports for paired-end data.
Nevertheless, I am sorry for being picky; I have found that macs2 reports are still not working correctly. The `.isValidMacs2CallpeakLog` function works fine, but the `.parseMacs2CallpeakLogs `function does not. Checking the code, I found that it's not sensitive to paired-end data. 

Reading some posts from macs2 developers, I get that when you use single-end data (or format BAM) macs2 models the fragment size and gives you a predicted value, but when you use paired-end data (or format BAMPE) the software takes the actual size of the fragment from the bam. So in the function `.parseMacs2CallpeakLogs` the lines where you grep for "predicted" values are not detected because they're missing and the information is in other lines like "mean fragment size is determined as 231.8 bp from treatment", and another change is that for single-end reads are called "reads", but for paired-end each read of the pair is called "fragment".

I know it's not an easy job to adapt the function for paired-end, but it would be great if you could do it because it's really nice to be able to get the reports of all the steps of a classical ChIP-seq analysis with your package, and just miss the peak calling for paired-end data.

Thank you again! :smile:

**Comment by steveped** [comment]
Hi again @LaureTomas ,

I've made some changes that seem to work pretty well with that example file, but I haven't pushed upstream to Bioconductor yet. The release version is currently at `https://github.com/steveped/ngsReports/tree/RELEASE_3_15` and you can install this using `BiocManager::install("steveped/ngsReports", ref = "RELEASE_3_15")`. I'd be really keen for you to give it a run on a few files if you have multiples. Might be easier to catch anything unexpected here, before I make it "Bioc Official"

Thanks again. Really pleased you're finding it useful too.

Steve

**Comment by LaureTomas** [comment]
Hi @steveped 

Great news!! I've tried the `RELEASE_3_15` with 50 files and it works like a charm! 

Thank you so much for being so quick to update the code! 
Waiting to see the updated version in Bioconductor :smile:
