### ISSUE TITLE
importNgsLogs Not working for type = "duplicationMetrics"

### ISSUE THREAD

**Issue by Teezi** [steveped/ngsReports#35]
Hi @steveped,

When I was using command `importNgsLogs(type = "duplicationMetrics")` to read in the Picard markDuplicates log files (i.e. metrics.txt), but failed. The errors are shown as below: 

```
Error in importNgsLogs(., type = "duplicationMetrics") : 
Incorrect file structure for: WT1_sorted_markdups_metrics.txt
Incorrect file structure for: WT2_sorted_markdups_metrics.txt
Incorrect file structure for: WT3_sorted_markdups_metrics.txt
Incorrect file structure for: WT4_sorted_markdups_metrics.txt
Incorrect file structure for: WT5_sorted_markdups_metrics.txt
Incorrect file structure for: Mut1_sorted_markdups_metrics.txt
Incorrect file structure for: Mut2_sorted_markdups_metrics.txt
Incorrect file structure for: Mut3_sorted_markdups_metrics.txt
Incorrect file structure for: Mut4_sorted_markdups_metrics.txt
Incorrect file structure for: Mut5_sorted_markdups_metrics.txt
```

**Comment by Teezi** [comment]
Just compared the `Sample1_Dedup_metrics.txt` file (from `ngsReports` R package) with my Picard markDuplicates `metrics.txt`, and realised that the words after `## htsjdk.samtools.metrics.StringHeader` were different.

`# picard.sam.markduplicates.MarkDuplicates ` in `Sample1_Dedup_metrics.txt` file,
`# MarkDuplicates` in my `metrics.txt` file.

Not sure if that helps...

**Comment by steveped** [comment]
Hi Teezi,
Thanks for alerting me. Can you please cut & paste the contents of one of these files directly here. Something unexpected has been found in the structure of the file which is causing that error and I really need to see the entire file so I can step through my checking process. Just one file will be enough. 
Thanks,
Steve

**Comment by steveped** [comment]
And just in case you're trying to email me, my email address has changed so please keep all communication regarding this issue on here

**Comment by Teezi** [comment]
![image](https://user-images.githubusercontent.com/42460339/178095401-41c3f09d-7cfd-41e0-8aa7-c4267f4bbc84.png)

**Comment by steveped** [comment]
HI Teezi.
As you may be aware, ngsReports parses text files, not png images. I cannot use this to debug the function. Can you please paste the contents of the file as requested.
Thanks

**Comment by Teezi** [comment]
Oops! my bad... now it is in text, hope it will help. 

Best wishes,
Teezi

**Comment by steveped** [comment]
Hi @Teezi 

I think I've resolved the issue now and the latest version on Bioc3.15 should update within the next 24 hours. Once you see a new version, appear, can you please give it a try & make sure it works on all of the files you were having trouble with?

Cheers,

Steve

**Comment by Teezi** [comment]
Hi @steveped 

Just test it, all good now!!

Cheers,
Teezi

**Comment by steveped** [comment]
Fantastic! Thanks for helping with that @Teezi.
